### PR TITLE
Feature/widescreen ultra

### LINKED ISSUE #832: Support more display aspect ratios
- 21:9 #776
- 32:9 #747

### PR DESCRIPTION
**Pull request by geosp**
Fixes #832

- [x] Fixed display issues with widescreen monitors.
- [x] Fixed display issues with settings table i.e. allow scrolling.
- [x] Allow settings to override system manufacturing and model. This is need when working on a custom system.
- [x] Add setting to mock IP address so that the real IP of the system is not displayed. Convenient when sharing the screen with other users.
- [x] Add the streaming module to the top right corner of the screen.
- [x] Added nontype clored theme.

edex-widescreen

edex-tron

### CODE REVIEW

**Comment by geosp** [comment]
I was thinking about adding color options to the terminal as a setting instead of a brand new theme. What do you think?

**Comment by geosp** [comment]
@GitSquared Thank you for this application. I find it useful even though some people may not think of it in terms of the functionality it offers. Great job.

**Comment by GitSquared** [comment]
Please make different PRs for each features.

**Comment by geosp** [comment]
Will do. Thanks for the review.

**Pull request closed without merging**
