### PR TITLE
Implement a text editor feature

### PR DESCRIPTION
**Pull request by Animus-Surge**
Not sure if this would be useful or not, but I added a text editor that you can use through the file system. You can click a file in the file explorer and it will open a popup that displays the filename (and extension), and the content of the file that's currently there. I've provided screenshots as well.

Capture
Open in the tron-disrupted theme

Capture2
Open in the red theme

Right now, the only kinds of files that can be opened are HTML, CSS, Javascript, XML, Yaml, Java, C#, C++ and H, Markdown, Batch and Shell, GDscript ([godot engine](https://godotengine.org/)), JSON (excludes the themes, keyboards, settings.json, and shortcuts.json), plain text, and log files, though that list can be expanded as needed.

In the future, I might try to make the different file types able to be differentiated by their icons, though that's a project for another day. I might also have the text inside the `textarea` a little bigger, and maybe always white, because the red theme is really hard to read from the default monospace font. Lmk if I need to make any changes

### CODE REVIEW

**Comment by EstoyMejor** [comment]
Looks good. I mean always could just use nano or whatever in the CLI, but another r option is another option I guess :D

**Comment by rodrigovssp** [comment]
#up

Em Seg, 9 de nov de 2020 21:38, Estoy Mejor <notifications@github.com>
escreveu:

**Comment by jvanslooten** [comment]
Just started using eDEX UI, this is pretty sweet

**Review by GitSquared — APPROVED** [review]
Hell, why not. Thanks!

**Pull request merged**
