### PR TITLE
💚 Fix: fix travis CI for macos & linux

### PR DESCRIPTION
**Pull request by Jabster28**

### CODE REVIEW

**Comment by Jabster28** [comment]
Actually @GitSquared, I was thinking of remaking the Travis CI in GitHub actions, would that be of any use to you?

**Comment by GitSquared** [comment]
@Jabster28 Was thinking about this too, + i think artifact retention on Actions works quite good?

Thanks a lot for taking a look into this!

**Comment by Jabster28** [comment]
No problem. I've been doing some work on it and I'm almost finished, should I rename this PR and force-push or just create a new one once I'm done?

**Comment by GitSquared** [comment]
Create a new one, I'll merge this one in the meantime.

**Review by GitSquared — APPROVED** [review]

**Pull request merged**
