### PR TITLE
Network Traffic Upload and Downlaod value

### PR DESCRIPTION
**Pull request by D4rkia**
I find graph only network traffic hard to read. Could be usefull to also display a numeric value.

### CODE REVIEW

**Comment by GitSquared** [comment]
Would you mind adding a screenshot to this PR?

**Review by aregon880 — APPROVED** [review]

**Comment by D4rkia** [comment]
Sure.

Screenshot_20201106_140645

**Comment by GitSquared** [comment]
Looks great! Merging.

**Review by marlonflore — COMMENTED** [review]
ODPF.SKy

**Review by chelsey8 — COMMENTED** [review]
😉

**Pull request merged**
