### PR TITLE
feat: more file types available in file editor (#975) #973

### PR DESCRIPTION
**Pull request by Animus-Surge**
Small update to the file editor I pushed a while ago, adding python and a few other extensions to the list of file types that are able to be opened by eDEX

### CODE REVIEW

**Comment by wrac4242** [comment]
created a pull request, adding more cases in. 
How does this deal with hidden files? the files that start with a `.`
and how would it deal with files without an extension

**Comment by Animus-Surge** [comment]
> How would this deal with hidden files?

As far as I know, if it's a supported file type, it should open it. (Now that I'm thinking about it I'm going to add `.gitattributes` and `.gitignore` files to the list of file types that can be opened in the file editor).

As for files without any extension, it doesn't open them. I suppose there could be a check somewhere that determines if the file has no extension, but I'm not sure where and why you'd need to edit them.

**Comment by wrac4242** [comment]
it looks like it failed because it could not update/install dependencies, there are a few, mirror not found errors

**Comment by GitSquared** [comment]
Don't worry about the linux builds, it's an external issue, i'll look into it.

**Review by GitSquared — CHANGES_REQUESTED** [review]
I feel like we may want to use mime-types, or an NPM library with file extensions, instead of managing dozens of file extensions ourselves. Could you look into this?

Some pointers:
 - https://www.npmjs.com/package/mime-types
 - https://www.iana.org/assignments/media-types/media-types.xhtml#text

**Comment by GitSquared** [comment]
> Don't worry about the linux builds, it's an external issue, i'll look into it.

I've fixed CI builds, by the way, you can rebase your PR to get green checkmarks :heavy_check_mark:

**Comment by Animus-Surge** [comment]
Gotcha. I’ll look into this.

**Comment by Animus-Surge** [comment]
Alright, now it's using MIME types to check the filetype. Only problem is now it opens binary files as well (files like Windows Desktop Shortcuts and DLLs), but for now at least it opens any registered file type.

**Review by GitSquared — APPROVED** [review]
I've pushed some changes to leverage [`mime.charset()`](https://github.com/jshttp/mime-types#mimecharsettype) as a way to tell which files are text-editable. Tell me what you think, this is mergeable for me.

**Comment by Animus-Surge** [comment]
Looks good to me! Think we're ready here.

**Comment by GitSquared** [comment]
@Animus-Surge @wrac4242 thanks for helping out!

**Pull request merged**
