### PR TITLE
feat: added a more detailed process view modal

### PR DESCRIPTION
**Pull request by KjartanOli**
Don't know how useful this will be, but I added a new modal which gives a more detailed listing of active processes. It is opened by clicking the top processes list.

edex

### CODE REVIEW

**Comment by GitSquared** [comment]
This is very cool!
Is this the list scrollable or fixed-length? Also, could we perhaps emphasize the title row by making the text bold before merging this?

**Comment by KjartanOli** [comment]
Made the header row bold, also removed it from the process name, and added a field at the end that shows the runtime of the process. As it stands, the list is fixed length at the top 30 processes, although I have been thinking about making it a config variable. I might also look into making it scrollable.
edex2

**Comment by GitSquared** [comment]
For the scroll, you might use the settings modal as an example.

**Comment by KjartanOli** [comment]
I made it a scrollable list of all processes returned by window.si.processes. Also applied the same css to the header row as the settings modal.
edex3

**Review by GitSquared — APPROVED** [review]
Great, thanks a lot! Merging.

**Pull request merged**
