### PR TITLE
Tracking is working under windows cmd

### PR DESCRIPTION
**Pull request by JaroslawPokropinski**
Tracking under windows is done with tlist dependency. Does not work with powershell (it keeps its 'location' separated from constant 'cwd')

### CODE REVIEW

**Comment by GitSquared** [comment]
I'm really excited about this one, this is one of the top requested features, I'm glad you found this.

**Comment by JaroslawPokropinski** [comment]
Tlist is part of debugging tools for windows. [docs.microsoft.com](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools).

**Comment by JaroslawPokropinski** [comment]
Sadly it seems that even git-bash doesnt work correctly with this method, even though cmd works just fine.

**Comment by JaroslawPokropinski** [comment]
With windows there is bundled tasklist.exe which doesnt have this funcionality.

**Comment by GitSquared** [comment]
(I'm going to let this wait a few days because I need to get a Windows machine back to test it.)

**Comment by GitSquared** [comment]
I'm sorry, but `tlist` just doesn't support enough shells, and after a good week of research, I still couldn't find a way to get a reliable `tlist.exe` upstream that we could trust.

Thanks for putting this together, even if it sadly didn't make it.

**Comment by JaroslawPokropinski** [comment]
I also wrote solution using regular expressions but it would react if some program would print paths in the same format (eg. C:\>)

**Comment by GitSquared** [comment]
@JaroslawPokropinski Yeah, I thought about that too, but it's not really usable either. Hopefully one day we'll have a reliable way of doing this.

**Pull request closed without merging**
