### PR TITLE
feat: audio, video and pdf reader

### PR DESCRIPTION
**Pull request by ghost-in-the-machine-86**
Implementing audio tag to play music and pdf reader with pdfjs [https://github.com/mozilla/pdf.js/](url) and custom buttons (zoom in/out and previous/next page)

### CODE REVIEW

**Comment by GitSquared** [comment]
Love the PDF reader! But the audio player seems kind of out-of-place. Could we perhaps style it to fit in a bit more?

**Comment by ghost-in-the-machine-86** [comment]
No problem! I can change it

**Review by marvinadante — APPROVED** [review]

**Comment by KjartanOli** [comment]
I've been doing some testing, and ogg files trigger the video player, not the audio player. Not sure if this is an issue at all.

**Comment by GitSquared** [comment]
Not ideal, but no blocking bug either, I'd say.

**Comment by KjartanOli** [comment]
Agreed, especialy since that happens because lstat reports the type as video.

**Comment by KjartanOli** [comment]
I made an attempt at creating controls for the audio player that fit more with the theme. I don't really like the way the volume controls look, but I haven't found a way to get any kind of speaker symbol that would respect the font colour of the user theme.
edex4
edex5

**Comment by GitSquared** [comment]
Woah, those look great. Any chance you two could coordinate on merging those changes? Otherwise, we'd go the two-PRs route.

**Comment by KjartanOli** [comment]
That should be possible. @ghost-in-the-machine-86 how would it be best to get these changes to you? Or were you already working on something similar?

**Comment by ghost-in-the-machine-86** [comment]
I did this media player, but i prefer your style @KjartanOli! Maybe i can add volume/progress bars to your player

Captura de tela de 2020-12-12 22-44-30

**Comment by KjartanOli** [comment]
Sounds great. I had no idea how to implement those. How should I send my code to you?

**Comment by ghost-in-the-machine-86** [comment]
Idk how can you change my code from here (my first pull request), so i invited you to my repository

**Comment by KjartanOli** [comment]
I just pushed my code to you develop branch.

**Comment by ghost-in-the-machine-86** [comment]
thanks!

**Comment by GitSquared** [comment]
You'll have to merge `develop` with `master` in the fork for changes to appear in this PR!

**Comment by ghost-in-the-machine-86** [comment]
Fixed ogg files to trigger audio player

**Comment by GitSquared** [comment]
Is this ready for review?

**Comment by ghost-in-the-machine-86** [comment]
Yes

**Review by GitSquared — APPROVED** [review]
image

Works great and looks amazing! Thanks guys.

**Pull request merged**
