### PR TITLE
Add greeting voice on MacOS

### PR DESCRIPTION
**Pull request by Raylin51**

### CODE REVIEW

**Comment by GitSquared** [comment]
systeminformation should already handle this. No need for an extra child process.

**Comment by GitSquared** [comment]
Wait, the greeting does not work on macOS? If so, the issue is with the systeminfo' package.

**Comment by Raylin51** [comment]
No, I just add the greeting voice on macOS with 'say' command, but I don't know how to execute 'say' command with systeminformation package.

**Comment by Raylin51** [comment]
The greeting text is working on macOS.

**Pull request closed without merging**
